default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: api_prosas_development

test:
  <<: *default
  database: api_prosas_test

production:
  <<: *default
  database: api_prosas_production
  username: api_prosas
  password: <%= ENV['API_PROSAS_DATABASE_PASSWORD'] %>
